/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef __H_SWS_WRAPPER_H__
#define __H_SWS_WRAPPER_H__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pumpkin_org_ffmpegwrapper_ffmpegwrapper
 * Method:    swsprocess
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_pumpkin_org_ffmpegwrapper_ffmpegwrapper_swsprocess
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif

#endif //__H_SWS_WRAPPER_H__
